### PR TITLE
Make recorder's `takeFullSnapshot` function public

### PR DESCRIPTION
**Pull request by lepsch**
# Ticket
https://www.notion.so/gitduck/Browser-sharing-If-someone-joins-a-call-after-someone-shared-its-browser-will-not-properly-see-it-4c9cef01859b41d28a068911d8aeae68

## Summary
Turn the private function `takeFullSnapshot` public so we can take snapshots when new-peers arrive.

### CODE REVIEW

**Review by drag0s — APPROVED** [review]
Looks good! I also prefer your approach but looks like a big change (in terms of diff). My only concern is that will be harder for us to upgrade the package in the future (ie. merge conflicts everytime).

**Comment by lepsch** [comment]
> Looks good! I also prefer your approach but looks like a big change (in terms of diff). My only concern is that will be harder for us to upgrade the package in the future (ie. merge conflicts everytime).

Yeah. At least `rrweb` is not that active so we can merge this single file easily when it conflicts.

**Comment by jlalmes** [comment]
Hi guys, hope you don't mind me looking through your repo's PRs. I was just about to start working on this task myself - would you guys mind me opening this as a PR in the core `rrweb-io/rrweb` repo?

**Comment by lepsch** [comment]
> Hi guys, hope you don't mind me looking through your repo's PRs. I was just about to start working on this task myself - would you guys mind me opening this as a PR in the core `rrweb-io/rrweb` repo?

No problem @provinceinnovation

**Pull request merged**
